services:
  p1monitor:
    container_name: p1monitor
    image: ghcr.io/eppin/p1monitor:main
    stop_grace_period: 1m
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 8080:80
    volumes:
      - ./data:/p1mon/data
      - ./usbdisk:/p1mon/mnt/usb
    tmpfs:
      - /run
      - /tmp
      - /p1mon/mnt/ramdisk
      - /var/log
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
